export const pricingTiers = [
  {
    name: "Bulk",
    price: "$65",
    frequency: "One Time",
    description: "Perfect for a quick boost to your job applications.",
    features: [
      "100 Job Applications",
      "One Time Payment",
      "Weekly Progress Reports",
    ],
    cta: "Get Bulk Applications",
    isPremium: false,
  },
  {
    name: "Custom",
    price: "$65",
    frequency: "/wk",
    description: "Tailored applications and LinkedIn support.",
    features: [
      "75 Tailored Resume Applications",
      "50 LinkedIn Easy Apply Weekly",
      "Personalized Support",
      "Weekly Progress Reports",
    ],
    cta: "Get Custom Plan",
    isPremium: true,
  },
  {
    name: "Pro",
    price: "$55",
    frequency: "/wk",
    description: "A high-volume of tailored applications and dedicated support.",
    features: [
      "75 Tailored Resume Applications",
      "50 LinkedIn Easy Apply Weekly",
      "Personalized Support",
      "Weekly Progress Reports",
    ],
    cta: "Go Pro",
    isPremium: false,
  },
  {
    name: "Monthly",
    price: "$240",
    frequency: "Monthly",
    description: "High-volume monthly applications with dedicated support.",
    features: [
      "400 Job Applications",
      "Monthly Payment",
      "Dedicated Support",
      "Weekly Progress Reports",
    ],
    cta: "Get Monthly Plan",
    isPremium: true,
  },
];
